### ISSUE TITLE
Support for Create Northstar and Creating Space Metals

### ISSUE THREAD

**Issue by KalWantsPizza** [AverageAnime/create-metalwork#22]
Hi, it would be awesome if you could add optional support for Create Northstar and Creating Space metals. A number of them already exist in other forms, which should help.

Northstar:
Martian Iron (raw, used to make Martian Steel with Volcanic Ash)
Martian Steel
Tungsten

Creating Space:
Nickel
Cobalt
Aluminum 

I started attempting to add compatibility for steel and Tungsten via datapack but it really doesn't work the way it should (or at all in the case of Tungsten).

Edit: Sorry - meant to tag as enhancement and I don't see a way to add via edit (on mobile at least)

**Comment by AverageAnime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Trello Tip: This is where assigned tasks live so that your team can see who's working on what and when it's due.](https://trello.com/c/NLFH4q6x/17-trello-tip-this-is-where-assigned-tasks-live-so-that-your-team-can-see-whos-working-on-what-and-when-its-due)
